### ISSUE TITLE
Modify code to process OKHs and OKWs into Informal Atom Lists....

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/project-data#18] opened 2022-11-02 00:09 UTC
We need a way to simply output new, unkown atoms from OKHs and OKWs. These will be process input to our mapping.

**Comment by devhawk** [comment] 2023-01-31 23:36
Is this a dupe of #19

**Comment by Jbutler-helpful** [comment] 2023-06-15 21:26
I think not only is it a dupe but I think the basics of this are done. I am closing this out.

**Closed as completed by Jbutler-helpful** 2023-06-15 21:26 UTC
